import type { Metadata } from "next";
import "../../src/app/globals.css";

import { Heading } from "./components/Heading";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >

        <Heading/>
        {children}
      </body>
    </html>
  );
}
